#!/usr/bin/env python3
"""Inventory AMDGPU hardware-facing intrinsics/features for SPIR-V review.

This tool intentionally does not claim that an AMDGPU intrinsic has a Vulkan
SPIR-V equivalent merely because LLVM can lower it to native ISA.  It extracts
candidate hardware-facing surfaces from an LLVM checkout and assigns only a
coarse review bucket.  The checked-in DXC support table remains authoritative.

Typical use on Windows:

  python utils/amd_spirv_inventory.py --llvm-root C:\\src\\llvm-project \
      --format markdown --output amd-native-inventory.md

The script is deliberately dependency-free so it can be used from a stock
Python installation while reviewing a newer LLVM checkout than the one DXC was
originally based on.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


FEATURE_RE = re.compile(
    r'defm\s+(?P<name>[A-Za-z0-9_]+)\s*:\s*AMDGPUSubtargetFeature\s*<\s*'
    r'"(?P<feature>[^"]+)"\s*,(?P<body>.*?)>\s*;',
    re.DOTALL,
)
INTRINSIC_RE = re.compile(r'\bdef\s+(int_amdgcn_[A-Za-z0-9_]+)\b')
STRING_RE = re.compile(r'"((?:\\.|[^"\\])*)"')


REVIEW_RULES = (
    (re.compile(r'(^|[_-])(m?q?sad|sad)([_-]|$)', re.I),
     'missing-spv-ingress',
     'SAD/MSAD/QSAD/MQSAD hardware family; no standardized SPIR-V SAD contract.'),
    (re.compile(r'(wmma|swmmac|mfma|mai)', re.I),
     'matrix-contract-review',
     'Matrix hardware family; map only where cooperative-matrix semantics match exactly.'),
    (re.compile(r'(^|[_-])dot[0-9_ -]*', re.I),
     'dot-contract-review',
     'Dot-product family; core/KHR integer-dot or cooperative-matrix coverage may be partial.'),
    (re.compile(r'(fp8|bf8|fp6|bf6|fp4|cvt.*norm|norm.*cvt)', re.I),
     'numeric-format-review',
     'Packed/low-precision conversion family; requires exact SPIR-V format/rounding review.'),
    (re.compile(r'(ray|bvh)', re.I),
     'ray-contract-review',
     'Ray-tracing family; high-level DXR maps to KHR, but private BVH operations need separate review.'),
    (re.compile(r'(permlane|dpp|swizzle|ballot|mbcnt)', re.I),
     'subgroup-contract-review',
     'Cross-lane/subgroup family; standard and AMD vendor operations cover only some semantics.'),
)


def review_bucket(text: str) -> tuple[str, str]:
    for pattern, bucket, note in REVIEW_RULES:
        if pattern.search(text):
            return bucket, note
    return 'unclassified', 'Needs manual native-contract classification.'


def parse_features(path: Path) -> list[dict[str, str]]:
    text = path.read_text(encoding='utf-8')
    rows: list[dict[str, str]] = []
    for match in FEATURE_RE.finditer(text):
        strings = STRING_RE.findall(match.group('body'))
        description = ''.join(strings).replace('\\"', '"')
        combined = ' '.join((match.group('name'), match.group('feature'), description))
        bucket, note = review_bucket(combined)
        rows.append({
            'kind': 'subtarget-feature',
            'name': match.group('name'),
            'feature': match.group('feature'),
            'description': description,
            'review_bucket': bucket,
            'note': note,
        })
    return rows


def parse_intrinsics(path: Path) -> list[dict[str, str]]:
    text = path.read_text(encoding='utf-8')
    rows: list[dict[str, str]] = []
    for name in sorted(set(INTRINSIC_RE.findall(text))):
        logical_name = name.removeprefix('int_').replace('_', '.')
        bucket, note = review_bucket(name)
        rows.append({
            'kind': 'llvm-intrinsic',
            'name': logical_name,
            'feature': '',
            'description': '',
            'review_bucket': bucket,
            'note': note,
        })
    return rows


def markdown(rows: list[dict[str, str]]) -> str:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row['review_bucket']] = counts.get(row['review_bucket'], 0) + 1

    out = [
        '# AMDGPU native-contract inventory',
        '',
        'Generated by `utils/amd_spirv_inventory.py`. This is an **inventory**,',
        'not a claim of Vulkan/SPIR-V support. `unclassified` means exactly that.',
        '',
        '## Review buckets',
        '',
    ]
    for bucket in sorted(counts):
        out.append(f'- `{bucket}`: {counts[bucket]}')
    out += [
        '',
        '## Entries',
        '',
        '| Kind | Name | LLVM feature | Review bucket | Description |',
        '| --- | --- | --- | --- | --- |',
    ]
    for row in rows:
        values = [
            row['kind'], row['name'], row['feature'], row['review_bucket'],
            row['description'],
        ]
        values = [value.replace('|', '\\|').replace('\n', ' ') for value in values]
        out.append('| ' + ' | '.join(values) + ' |')
    out.append('')
    return '\n'.join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--llvm-root', required=True, type=Path,
                        help='root of an llvm-project checkout')
    parser.add_argument('--format', choices=('markdown', 'json'), default='markdown')
    parser.add_argument('--output', type=Path)
    parser.add_argument('--interesting-only', action='store_true',
                        help='omit entries that are still unclassified')
    args = parser.parse_args()

    feature_path = args.llvm_root / 'llvm/lib/Target/AMDGPU/AMDGPU.td'
    intrinsic_path = args.llvm_root / 'llvm/include/llvm/IR/IntrinsicsAMDGPU.td'
    missing = [str(path) for path in (feature_path, intrinsic_path) if not path.is_file()]
    if missing:
        parser.error('missing LLVM AMDGPU source file(s): ' + ', '.join(missing))

    rows = parse_features(feature_path) + parse_intrinsics(intrinsic_path)
    rows.sort(key=lambda row: (row['review_bucket'], row['kind'], row['name']))
    if args.interesting_only:
        rows = [row for row in rows if row['review_bucket'] != 'unclassified']

    if args.format == 'json':
        rendered = json.dumps(rows, indent=2) + '\n'
    else:
        rendered = markdown(rows)

    if args.output:
        args.output.write_text(rendered, encoding='utf-8')
    else:
        print(rendered, end='')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
